### ISSUE TITLE
README: Add Problem Statement

### ISSUE THREAD

**Issue by ginabeki** [kaka-ruto/carpitan#11]
I appreciate this project and the functionalities it offers ✨ . I noticed that the README could be improved to attract new contributors.
Specifically, it would be helpful to add a clear explanation of the problem this project solves. This would give potential contributors a better understanding of the project's purpose and how their contributions can make a difference.

**Comment by kaka-ruto** [comment]
Thanks @ginabeki . I've created a PR with the info. We could add more goals of course. Let me know what you think! https://github.com/kaka-ruto/carpitan/pull/12

**Comment by ginabeki** [comment]
@kaka-ruto This looks great! #12 ✅ 
Adding the goals clarifies the project's purpose. Thanks for taking my suggestion into account!
