### ISSUE TITLE
Direct Democracy Tool for Carpitan

### ISSUE THREAD

**Issue by newton-migosi** [kaka-ruto/carpitan#22]
Proposing a polling section for members to vote on ideas shared within the community. We could clone or licence a tool like FeedBear (feedbear.com)

Requirements
- Open proposal of ideas (just fill a form)
- Upvotes and downvotes with a running tally

For Auth it would be nice to have sth like an ID scans so each account is really tied to a single ID but they can be anonymous when voting.

**Comment by kaka-ruto** [comment]
Good suggestion. Do you think the suggestion on this similar issue will solve the problem? https://github.com/kaka-ruto/carpitan/issues/15
