### ISSUE TITLE
Dev env set up issues

### ISSUE THREAD

**Issue by Annastacia-dev** [kaka-ruto/carpitan#29]
I'm trying to set up a development env, I've followed the set up instructions but I'm running into a few issues
When I run `bin/dev` I get this error
```
Segmentation fault (core dumped)
```

When I run `rails s`

```
ActionView::Template::Error (couldn't find file 'trix/dist/trix' with type 'text/css'
```

Anyone else who has run into the same issues and was able to solve or knows the solution ?

**Comment by kaka-ruto** [comment]
Hi @Annastacia-dev , what OS are you on? For the last error it seems action text was not well installed. Was your `bin/setup` successful?

Could you also post the whole stack trace(logs) from when the error started to the end of it

**Comment by Annastacia-dev** [comment]
Hello @kaka-ruto 

I'm on Ubuntu and yes `bin/setup` was successful, see attached screenshots.

![Screenshot from 2024-08-05 12-12-22](https://github.com/user-attachments/assets/06d0d09e-efa2-4d89-b15e-a852a73031f1)
![Screenshot from 2024-08-05 12-09-52](https://github.com/user-attachments/assets/0bb86719-02d9-4e28-a13a-071957ec64c4)

**Comment by kaka-ruto** [comment]
Could you change this line `Rails.application.config.assets.paths << Rails.root.join("node_modules/bootstrap-icons/font")
` in `config/initializers/assets.rb` to `Rails.application.config.assets.paths << Rails.root.join('node_modules')` and see if `bin/dev` or ` bin/rails s` works?

**Comment by Annastacia-dev** [comment]
`bin/rails s`

![Screenshot from 2024-08-05 13-26-44](https://github.com/user-attachments/assets/53f0ca03-8b91-4587-be45-53acef89dda1)

**Comment by kaka-ruto** [comment]
How about commenting out the line completely? And restart the server.

```rb
# config/initializers/assets.rb
# Rails.application.config.assets.paths << Rails.root.join("node_modules/bootstrap-icons/font")
```

**Comment by Annastacia-dev** [comment]
It was a yarn issue actually 
I have installed yarn and `bin/rails s` works now `bin/dev` still has the same response

Will work with this for now but I'm not sure it will be able to watch for changes when it comes to the view code changes

**Comment by kaka-ruto** [comment]
Glad you figured it. I don't get the same so I have to rely on your findings :) What do you get when you run `yarn build` on your terminal

**Comment by Annastacia-dev** [comment]
```
$ yarn build
yarn run v1.22.22
$ node esbuild.config.mjs
Done in 0.74s.
```

**Comment by kaka-ruto** [comment]
That means js is building correctly. How about `yarn build:css`? If that works as well, then `bin/dev` should work, ideally! Because bin/dev is running all the above commands at a ago (via the `procfile.dev`)

**Comment by Annastacia-dev** [comment]
`yarn build:css` also compiles fine but `bin/dev` still fails with the same `segfault` error, I'll default to `foreman start -f Procfile.dev` because it works , I think the `segfault` error is code unrelated from the solutions I've seeked ( although none has worked 🤣)

**Comment by kaka-ruto** [comment]
Okay, thank you :), I will keep watching if more people face the same issue.
